version = "0.1"
package = "changemap"
license = "GPL"
title = "Change Visualization Functions"
depends = "terrame (>= 2.0)"
authors = "Bernardo M. de Rezende, Pedro R. Andrade, Rodrigo Avancini and Tiago, G. S. Carneiro"
contact = "marottabernardo@gmail.com"
content = "Implements functions where the change happening in the process can be visualized in maps as attributes"